# Which BEL names are global buffers for nextpnr?
global_buffer_bels: []
# How should nextpnr lump BELs during analytic placement?
buckets:
- bucket: LUTS
  cells:
    - LUT4
- bucket: FFS
  cells:
    - FD1P3BX
    - FD1P3DX
    - FD1P3IX
    - FD1P3JX
- bucket: IOBs
  cells:
   - IB
   - OB
