# Which BEL names are global buffers for nextpnr?
global_buffer_bels:
- BUFG
- BUFGCTRL
- VCC
- GND
# Which cell names are global buffers, and which pins should use dedicated routing resources
global_buffer_cells:
  - cell: BUFG
    pins: # list of pins that use global resources
     - name: I # pin name
       guide_placement: true # attempt to place so that this pin can use dedicated resources
       max_hops: 10 # max hops of interconnect to search (10 is for test purposes and may need to be refined)
     - name: O
       force_dedicated_routing: true # the net connected to this pin _must_ use dedicated routing only
  - cell: BUFGCTRL
    pins:
      - name: I0
        guide_placement: true
        max_hops: 10
      - name: I1
        guide_placement: true
        max_hops: 10
      - name: O
        force_dedicated_routing: true
# How should nextpnr lump BELs during analytic placement?
buckets:
- bucket: FLIP_FLOPS
  cells:
   - FDRE
- bucket: LUTS
  cells:
   - LUT1
- bucket: BRAMS
  cells:
   - RAMB18E1
   - RAMB36E1
   - FIFO18E1
   - FIFO36E1
- bucket: BUFG
  cells:
   - BUFG
   - BUFGCTRL
- bucket: BUFH
  cells:
   - BUFH
   - BUFHCE
- bucket: BUFMR
  cells:
   - BUFMR
- bucket: BUFR
  cells:
   - BUFR
- bucket: IBUFs
  cells:
   - IBUF
   - IBUFDS_IBUFDISABLE_INT
- bucket: OBUFs
  cells:
   - OBUF
   - OBUFTDS
- bucket: MMCM
  cells:
   - MMCME2_ADV
- bucket: PLL
  cells:
   - PLLE2_BASE
- bucket: PULLs
  cells:
   - PULLDOWN
- bucket: CARRY
  cells:
   - MUXCY
   - XORCY
   - CARRY4
# don't route through the following cells
disabled_routethroughs:
  - BUFGCTRL
  - BUFR
# Do not allow cells to be placed at BELs
disabled_cell_bel_map:
  - cell: FDRE
    bels:
     - TFF
     - IFF
     - OUTFF
  - cell: FDCE
    bels:
     - TFF
     - IFF
     - OUTFF
  - cell: FDPE
    bels:
     - TFF
     - IFF
     - OUTFF
